spring.application.name=organizer
spring.messages.encoding=UTF-8
spring.messages.basename=messages

bot.telegram.token=${BOT_TELEGRAM_TOKEN}
max.bot.token=${BOT_MAX_TOKEN}

proxy.host=${PROXY_HOST}
proxy.port=${PROXY_PORT}
proxy.user=${PROXY_USERNAME}
proxy.pass=${PROXY_PASSWORD}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

