create table app_users (
                           is_blocked boolean,
                           is_deleted boolean,
                           created_at timestamp(6),
                           id bigint generated by default as identity primary key,
                           current_screen varchar(255),
                           identification_code varchar(255),
                           last_active_platform varchar(255) constraint app_users_last_active_platform_check
                               check ((last_active_platform)::text = ANY ((ARRAY ['TELEGRAM'::character varying, 'MAX'::character varying])::text[]))
);

create table platform_accounts (
                                   is_deleted boolean not null,
                                   id bigint generated by default as identity primary key,
                                   user_id bigint not null constraint fk_platform_account_user references app_users,
                                   platform varchar(255) not null constraint platform_accounts_platform_check
                                       check ((platform)::text = ANY ((ARRAY ['TELEGRAM'::character varying, 'MAX'::character varying])::text[])),
                                   platform_user_id varchar(255) not null,
                                   unique (platform, platform_user_id)
);

create table tasks (
                       is_completed boolean not null,
                       is_important boolean not null,
                       app_user_id bigint not null constraint fk_task_user references app_users,
                       created_at timestamp(6) not null,
                       deadline timestamp(6),
                       id bigint generated by default as identity primary key,
                       description text,
                       title varchar(255) not null
);

create table reminders (
                           is_sent boolean,
                           id bigint generated by default as identity primary key,
                           reminder_time timestamp(6) not null,
                           task_id bigint not null constraint fk_reminder_task references tasks
);