CREATE TABLE auth_codes (
                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            code VARCHAR(6) NOT NULL,
                            user_id bigint NOT NULL,
                            created_at TIMESTAMP(6) NOT NULL,
                            expires_at TIMESTAMP(6) NOT NULL,
                            is_used BOOLEAN NOT NULL DEFAULT FALSE,

                            CONSTRAINT code_format_check CHECK (code ~ '^[A-Z0-9]{6}$'),
                            CONSTRAINT fk_auth_code_user FOREIGN KEY (user_id) REFERENCES app_users (id)
);
CREATE INDEX idx_auth_code_lookup ON auth_codes(code);